version: 2.2.0.{build}
image: Visual Studio 2017

branches:
  only:
    - master
configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.ImageManager
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  
install:
  - nuget update -Self

before_build:
  - appveyor-retry nuget restore -Verbosity quiet
build:
  project: $(PROJECT).sln
  verbosity: minimal